SECRETS_FILE: "/home/username/.config/restic-wrapper.yaml" # allowed empty

ENDPOINT: storage.yandexcloud.net
BUCKET: "some-bucket-name"
BUCKET_DIR: "" # allowed empty

BACKUP_PATHS:
  - "/home/username/Desktop"
  - "/home/username/Documents"
