profiles:
  work-profile:
    endpoint: "storage.yandexcloud.net"
    bucket: "some-bucket"
    bucket-dir: ""
    secrets-file: "/etc/restic-wrapper/work-secrets.yaml"
    sources:
      - "/home/user/Documents"
  personal-profile:
    endpoint: "s3.amazon.com"
    bucket: "a-pretty-bucket"
    bucket-dir: "path/within/bucket"
    secrets-file: "/home/user/.config/personal-secrets.yaml"
    sources:
      - "/home/user/Desktop"
      - "/home/user/Videos"
